# Generated by Django 3.0.3 on 2020-02-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is test for product description'),
            preserve_default=False,
        ),
    ]
